version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save

  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            IMAGE_NAME=nodejswebapp1:$TIMESTAMP
            echo "Building Docker image with tag: $TIMESTAMP"
            docker build -t $IMAGE_NAME -t arjun0201/nodejswebapp1:$TIMESTAMP -t arjun0201/nodejswebapp1:latest .
            echo $DOCKER_PASSWORD | docker login -u arjun0201 --password-stdin
            docker push arjun0201/nodejswebapp1:$TIMESTAMP
            docker push arjun0201/nodejswebapp1:latest
            echo "Image pushed with tag: $TIMESTAMP"
            echo $TIMESTAMP > /tmp/timestamp.txt
      - run:
          name: Verify timestamp.txt file
          command: |
            echo "Contents of /tmp/timestamp.txt:"
            cat /tmp/timestamp.txt
            echo "Listing /tmp directory:"
            ls -l /tmp
      - persist_to_workspace:
          root: /tmp
          paths:
            - timestamp.txt

  run_docker_container:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Verify Workspace Contents
          command: |
            echo "Workspace contents:"
            ls -l /workspace
            echo "Contents of /workspace/timestamp.txt:"
            cat /workspace/timestamp.txt
      - run:
          name: Run Docker container with timestamp
          command: |
            TIMESTAMP=$(cat /workspace/timestamp.txt)
            echo "Running Docker container with image tag: $TIMESTAMP"
            docker run -d --name nodejs123 -p 8081:8081 arjun0201/nodejswebapp1:$TIMESTAMP

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_test
      - build_docker_image
      - run_docker_container:
          requires:
            - build_docker_image
