version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save

  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            IMAGE_NAME=nodejswebapp1:$TIMESTAMP
            docker build -t $IMAGE_NAME -t arjun0201/nodejswebapp1:$TIMESTAMP -t arjun0201/nodejswebapp1:latest .
            echo $DOCKER_PASSWORD | docker login -u arjun0201 --password-stdin
            docker push arjun0201/nodejswebapp1:$TIMESTAMP
            docker push arjun0201/nodejswebapp1:latest

workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image
