version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save

  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            IMAGE_NAME=nodejswebapp1:build-$CIRCLE_BUILD_NUM
            echo "Building Docker image with tag: build-$CIRCLE_BUILD_NUM"
            docker build -t $IMAGE_NAME -t arjun0201/nodejswebapp1:build-$CIRCLE_BUILD_NUM -t arjun0201/nodejswebapp1:latest .
            echo $DOCKER_PASSWORD | docker login -u arjun0201 --password-stdin
            docker push arjun0201/nodejswebapp1:build-$CIRCLE_BUILD_NUM
            docker push arjun0201/nodejswebapp1:latest
            echo "Image pushed with tag: build-$CIRCLE_BUILD_NUM"
            echo $CIRCLE_BUILD_NUM > /tmp/build_number.txt
      - persist_to_workspace:
          root: /tmp
          paths:
            - build_number.txt

  run_docker_container:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Verify Workspace Contents
          command: |
            echo "Workspace contents:"
            ls -l /workspace
            echo "Contents of /workspace/build_number.txt:"
            cat /workspace/build_number.txt
      - run:
          name: Run Docker container with build number
          command: |
            BUILD_NUMBER=$(cat /workspace/build_number.txt)
            CONTAINER_NAME=nodejs123_$BUILD_NUMBER
            echo "Running Docker container with name: $CONTAINER_NAME"
            docker run -d --name $CONTAINER_NAME -p 8081:8081 arjun0201/nodejswebapp1:build-$BUILD_NUMBER

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_test
      - build_docker_image
      - run_docker_container:
          requires:
            - build_docker_image
